version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://roshanbalraut:F16H7SEKyf85EhBi@65.2.168.241/?ssl=true&replicaSet=atlas-lutz88-shard-0&authSource=admin&retryWrites=true&w=majority

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
